import Head from "next/head";
import Curve from "@/components/Layout/Curve";
import Contactx from "../components/Layout/Contact/index";
import RoundedButton from "../components/Layout/RoundedButton";
import Link from "next/link";
import dynamic from "next/dynamic";

// Dynamically import the Landing component
const Land = dynamic(() => import("../components/Layout/Landing/index"), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <Curve backgroundColor={"#f5fbff"}>
          <h1 className="text-center font-black text-9xl pb-5">Loop</h1>
          <h2 className="text-center font-black text-7xl py-5 ">
            The gateway to fast and effective txn of liquidity
          </h2>
          <div className="body">
            <p>
              Fusce tristique nisi eu sodales suscipit. Praesent ante ipsum,
              suscipit eu dapibus in, tincidunt et massa. Sed pulvinar consequat
              elit at placerat. Maecenas bibendum in purus sed hendrerit.
              Integer efficitur mattis consectetur. Sed sagittis tortor non
              mauris laoreet ultrices. Nunc sit amet sem suscipit, accumsan
              justo sed, laoreet odio. Phasellus pharetra arcu nibh, non
              scelerisque ipsum rutrum quis. Fusce quis commodo leo. Mauris ut
              congue mauris.
            </p>
            <p>
              Duis tempus risus ut est malesuada, sit amet auctor tortor tempus.
              Sed luctus, odio a vulputate elementum, nulla enim bibendum ipsum,
              in ornare elit nisi quis tortor. Nullam quis condimentum tellus.
              Nullam non eros sem. Cras molestie convallis dolor, quis egestas
              turpis congue in. Maecenas ut tellus at nunc consectetur
              facilisis. Vivamus ornare ex a nibh egestas, id euismod mi
              euismod.
            </p>
            <p>
              Duis tempus risus ut est malesuada, sit amet auctor tortor tempus.
              Sed luctus, odio a vulputate elementum, nulla enim bibendum ipsum,
              in ornare elit nisi quis tortor. Nullam quis condimentum tellus.
              Nullam non eros sem. Cras molestie convallis dolor, quis egestas
              turpis congue in. Maecenas ut tellus at nunc consectetur
              facilisis. Vivamus ornare ex a nibh egestas, id euismod mi
              euismod.
            </p>
          </div>
          <div className="mt-10 mb-[12.5rem] grid  grid-rows-3 grid-flow-row gap-3 ">
            <div className=" grid place-items-center">
              <div>bla bla hello</div>
            </div>
            <div className=" grid place-items-start">
              <div>bla bla hello</div>
            </div>
            <div className="grid place-items-end">
              <div>bla bla hello</div>
            </div>
          </div>

          <div className=" mt-10 grid grid-rows-4 grid-cols-2 gap-5 ">
            <div className="grid row-span-3 bg-green-300">x1</div>
            <div className="">x2</div>
            <div className="bg-slate-400">x3</div>
            <div className="grid row-span-2 bg-blue-500">x4</div>
            <div className="">x5</div>
            <div className="grid row-span-"></div>
          </div>
          <Land />
        </Curve>
        <div className="text-blue-50 px-[2.5rem] py-[2rem] flex justify-evenly">
          <RoundedButton>
            <p className="py-4 font-semibold ">
              <Link href="/about">About</Link>
            </p>
          </RoundedButton>
          <RoundedButton>
            <p className="py-4 font-semibold ">
              <Link href="/contact">Get in touch</Link>
            </p>
          </RoundedButton>

          <RoundedButton>
            <p className="py-4 font-semibold ">
              <Link href="/faq">FAQ</Link>
            </p>
          </RoundedButton>
          <RoundedButton>
            <p className="py-4 font-semibold ">
              <Link href="/privacypolicy">Privacy Policy</Link>
            </p>
          </RoundedButton>
        </div>
        <div>
          <Contactx />
        </div>
      </div>
    </>
  );
}
